### ISSUE TITLE
cannot determine chrome version

### ISSUE THREAD

**Issue by at-inoue** [maedadev/itamae-plugin-recipe-selenium#3]
Trying to get the chrome version in the wrong order will result in an error.

```
$ sudo bundle exec itamae local --ohai recipe.rb

 INFO : Starting Itamae... 
 INFO : Loading node data via ohai...
ERROR :   Command `sudo yum list | grep google-chrome-stable` failed. (exit status: 1)
bundler: failed to load command: itamae (/usr/local/bin/itamae)
Itamae::Backend::CommandExecutionError: Itamae::Backend::CommandExecutionError
  /usr/local/lib/ruby/gems/2.5.0/gems/itamae-1.10.6/lib/itamae/backend.rb:82:in `run_command'
  /usr/local/lib/ruby/gems/2.5.0/gems/itamae-1.10.6/lib/itamae/recipe.rb:150:in `run_command'
...
```

* Current Order

  1. get the chrome version
  2. install yum repository for chrome
  3. install (or update) chrome package
  
* Want Order

  1. install yum repository for chrome
  2. install (or update)  chrome package
  3. get the chrome version

**Comment by ichylinux** [comment]
@at-inoue so, is this still an open issue?

**Comment by at-inoue** [comment]
Sorry. Close immediately!
